# Setup script to configure VITE_API_BASE for network access
param(
    [string]$NetworkIP = $null
)

Write-Host "🔧 Setting up network environment for ReactAgent" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green
Write-Host ""

# Get local IP if not provided
if (-not $NetworkIP) {
    Write-Host "Detecting local network IP address..." -ForegroundColor Yellow

    # Get all IPv4 addresses
    $ipAddresses = Get-NetIPAddress -AddressFamily IPv4 | Where-Object {
        $_.IPAddress -notlike "127.*" -and
        $_.IPAddress -notlike "169.254.*" -and
        $_.PrefixOrigin -ne "WellKnown"
    }

    if ($ipAddresses.Count -eq 0) {
        Write-Host "❌ No suitable network IP address found" -ForegroundColor Red
        Write-Host "Please provide your network IP manually:" -ForegroundColor Yellow
        Write-Host ".\\setup-network-env.ps1 -NetworkIP 'YOUR_IP_ADDRESS'" -ForegroundColor Cyan
        exit 1
    }

    # Use the first available IP
    $NetworkIP = $ipAddresses[0].IPAddress
    Write-Host "Found IP: $NetworkIP" -ForegroundColor Green
}

# Validate IP format
if ($NetworkIP -notmatch '^(\d{1,3}\.){3}\d{1,3}$') {
    Write-Host "❌ Invalid IP address format: $NetworkIP" -ForegroundColor Red
    exit 1
}

# Create .env.local with the correct IP
$envContent = "# Network configuration - Auto-generated by setup-network-env.ps1`nVITE_API_BASE=http://$NetworkIP`:8080"

Write-Host "Creating .env.local with network configuration..." -ForegroundColor Yellow
$envContent | Out-File -FilePath ".env.local" -Encoding UTF8 -Force

Write-Host "✅ Successfully created .env.local" -ForegroundColor Green
Write-Host "   VITE_API_BASE=http://$NetworkIP`:8080" -ForegroundColor Cyan
Write-Host ""

Write-Host "📱 Network Access Instructions:" -ForegroundColor Green
Write-Host "============================" -ForegroundColor Green
Write-Host "1. Make sure your backend is running with network access:" -ForegroundColor White
Write-Host "   .\backend-spring\restart-network.bat" -ForegroundColor Cyan
Write-Host ""
Write-Host "2. Start the frontend:" -ForegroundColor White
Write-Host "   .\reactagent-frontend\scripts\test-frontend-network.sh" -ForegroundColor Cyan
Write-Host ""
Write-Host "3. On your mobile device, access:" -ForegroundColor White
Write-Host "   http://$NetworkIP`:5173" -ForegroundColor Cyan
Write-Host ""
Write-Host "4. Test the connection:" -ForegroundColor White
Write-Host "   .\backend-spring\test-frontend-connection.bat" -ForegroundColor Cyan
Write-Host ""

Write-Host "🎯 What this fixes:" -ForegroundColor Green
Write-Host "- ✅ Dynamic IP detection" -ForegroundColor White
Write-Host "- ✅ Automatic .env.local configuration" -ForegroundColor White
Write-Host "- ✅ Works with any network IP changes" -ForegroundColor White
Write-Host "- ✅ No manual IP updates needed" -ForegroundColor White
