#!/bin/bash

# Setup script to configure VITE_API_BASE for network access
# Usage: ./setup-network-env.sh [NETWORK_IP]

echo "🔧 Setting up network environment for ReactAgent"
echo "=================================================="
echo ""

# Get local IP if not provided
if [ -z "$1" ]; then
    echo "Detecting local network IP address..."

    # Try different methods to get local IP
    if command -v hostname &> /dev/null; then
        NETWORK_IP=$(hostname -I | awk '{print $1}')
    elif command -v ip &> /dev/null; then
        NETWORK_IP=$(ip route get 8.8.8.8 | sed -n 's/.*src \([0-9.]*\).*/\1/p' | head -1)
    else
        NETWORK_IP=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | head -1 | cut -d' ' -f2 | cut -d':' -f2)
    fi

    if [ -z "$NETWORK_IP" ] || [ "$NETWORK_IP" = "127.0.0.1" ]; then
        echo "❌ Could not automatically detect network IP"
        echo "Please provide your network IP manually:"
        echo "   ./setup-network-env.sh YOUR_IP_ADDRESS"
        exit 1
    fi

    echo "Found IP: $NETWORK_IP"
else
    NETWORK_IP="$1"
fi

# Validate IP format
if ! echo "$NETWORK_IP" | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$' >/dev/null; then
    echo "❌ Invalid IP address format: $NETWORK_IP"
    exit 1
fi

# Create .env.local with the correct IP
cat > .env.local << EOF
# Network configuration - Auto-generated by setup-network-env.sh
VITE_API_BASE=http://$NETWORK_IP:8080
EOF

echo "✅ Successfully created .env.local"
echo "   VITE_API_BASE=http://$NETWORK_IP:8080"
echo ""
echo "📱 Network Access Instructions:"
echo "============================"
echo "1. Make sure your backend is running with network access:"
echo "   ./backend-spring/restart-network.sh"
echo ""
echo "2. Start the frontend:"
echo "   ./reactagent-frontend/scripts/test-frontend-network.sh"
echo ""
echo "3. On your mobile device, access:"
echo "   http://$NETWORK_IP:5173"
echo ""
echo "4. Test the connection:"
echo "   ./backend-spring/test-frontend-connection.sh"
echo ""
echo "🎯 What this fixes:"
echo "- ✅ Dynamic IP detection"
echo "- ✅ Automatic .env.local configuration"
echo "- ✅ Works with any network IP changes"
echo "- ✅ No manual IP updates needed"
